version: '3'

services:
  couchbase:
    image: couchbase
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210 
    networks:
        - mentor-network  
  elastic:
    image: elasticsearch:7.9.2
    environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
    networks:
        - mentor-network
    ports:
        - 9200:9200
        - 9300:9300
  
  mentorapp-serviceregistry:
    image: mentorapp-serviceregistry
    ports:
        - 8761:8761
    build:  mentorapp-serviceregistry/
    networks:
        - mentor-network
        
  mentorapp-cloudgateway:
    image: mentorapp-cloudgateway
    ports:
        - 8080:8080
    build:  mentorapp-cloudgateway/
    networks:
        - mentor-network
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://mentorapp-serviceregistry:8761/eureka   
      
  mentorapp-user:
    image: mentorapp-user
    ports:
        - 8081:8081
    build:  mentorapp-user/
    depends_on:
        - couchbase
        - mentorapp-serviceregistry
        - mentorapp-cloudgateway
    networks:
        - mentor-network
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://mentorapp-serviceregistry:8761/eureka       
        SPRING_COUCHBASE_BOOTSTRAP_HOSTS: couchbase
        
  mentorapp-expertise:
    image: mentorapp-expertise
    ports:
        - 8082:8082
    build:  mentorapp-expertise/
    depends_on:
        - elastic
        - mentorapp-serviceregistry
        - mentorapp-cloudgateway
    networks:
        - mentor-network
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://mentorapp-serviceregistry:8761/eureka    
        SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS: http://elastic:9200
        SPRING_ELASTICSEARCH_REST_URIS: http://elastic:9200
        
   mentorapp-admin:
    image: mentorapp-admin
    ports:
        - 8761:8761
    build:  mentorapp-admin/
    networks:
        - mentor-network
  mentorapp-ui:
    image: mentorapp-ui
    ports:
        - 8077:80
    build:  mentorapp-ui/
    networks:
        - mentor-network
networks:
    mentor-network:
        driver: bridge
  